import { runQuery, getDatabase, logAction, getAllQuery } from '../database';
import { getCompanyInfo } from '../scraper-service';
import * as fs from 'fs';
import * as path from 'path';
let app: any;
try { app = require('electron').app; } catch (e) { app = (global as any).electronApp; }

// Get base documents directory.
// If the user has configured a storage path (Settings > Storage), we MUST save there.
// Otherwise fallback to app.getPath('userData')/generated_docs.
const getBaseDocsDir = () => {
  try {
    const db = getDatabase();
    const settings = (db.settings || [])[0] || {};
    const configuredRoot = settings.storage_path || settings.storagePath;
    const root = configuredRoot && String(configuredRoot).trim().length > 0
      ? String(configuredRoot).trim()
      : path.join(app.getPath('userData'), 'generated_docs');

    if (!fs.existsSync(root)) {
      fs.mkdirSync(root, { recursive: true });
    }

    return root;
  } catch {
    // Ultra-safe fallback
    const fallback = path.join(app.getPath('userData'), 'generated_docs');
    if (!fs.existsSync(fallback)) fs.mkdirSync(fallback, { recursive: true });
    return fallback;
  }
};

// Get organized documents directory:
// [StorageRoot]/Company/Position/YYYY-MM-DD
const getOrganizedDocsDir = (companyName: string, position: string, dateFolder: string) => {
  // Sanitize folder names (remove invalid characters)
  const sanitize = (str: string) => String(str || '').replace(/[<>:"/\\|?*]/g, '_').trim().substring(0, 50);

  const company = sanitize(companyName || 'Unknown_Company');
  const pos = sanitize(position || 'Unknown_Position');
  const date = sanitize(dateFolder || 'Unknown_Date');

  const docsPath = path.join(getBaseDocsDir(), company, pos, date);
  if (!fs.existsSync(docsPath)) {
    fs.mkdirSync(docsPath, { recursive: true });
  }
  return docsPath;
};

// Legacy: Get simple documents directory (for backwards compatibility)
const getDocsDir = () => getBaseDocsDir();

/**
 * Get the profile data based on Thinker's source setting
 */
async function getProfileByThinkerSource(userId: number, thinker: any): Promise<any> {
  const source = thinker?.thinker_source || 'all';
  const db = getDatabase();
  
  // Get all profiles
  const profiles = db.user_profile || [];
  const linkedinProfile = profiles.find((p: any) => p.source === 'linkedin');
  const manualProfile = profiles.find((p: any) => p.source === 'manual');
  const baseProfile = profiles[0];
  
  // Get uploaded CVs
  const documents = db.documents || [];
  const uploadedCvs = documents.filter((d: any) => d.doc_type === 'uploaded_cv');
  
  let selectedProfile = baseProfile;
  
  switch (source) {
    case 'linkedin':
      if (linkedinProfile) {
        selectedProfile = linkedinProfile;
      }
      break;
    case 'manual':
      if (manualProfile) {
        selectedProfile = manualProfile;
      }
      break;
    case 'uploaded_cv':
      // For uploaded CVs, use base profile with CV data integrated
      if (uploadedCvs.length > 0) {
        selectedProfile = baseProfile;
        // Note: CV content could be parsed and integrated here
      }
      break;
    case 'all':
    default:
      // Combine all sources (default behavior)
      selectedProfile = baseProfile;
      break;
  }
  
  return selectedProfile;
}

/**
 * Build verification prompt for Auditor to check forced documents
 */
function buildVerificationPrompt(docKey: string, docLabel: string, content: string, userProfile: any): string {
  return `You are the "Auditor" agent. A document was forcefully generated by user override. Your job is to verify it doesn't contain FABRICATED information.

DOCUMENT TYPE: ${docLabel}

USER'S ACTUAL PROFILE DATA:
Name: ${userProfile?.name || 'Unknown'}
Title: ${userProfile?.title || 'Unknown'}
Skills: ${userProfile?.skills || 'Not provided'}
Experiences: ${JSON.stringify(userProfile?.experiences || []).substring(0, 500)}

GENERATED CONTENT TO VERIFY:
${content}

CHECK FOR:
1. Are there any job titles, companies, or dates mentioned that are NOT in the user's profile?
2. Are there any specific achievements or metrics that seem fabricated?
3. Are there any skills or certifications not mentioned in the profile?

RESPONSE FORMAT:
If the content appears accurate to the profile data: "VERIFIED: Content matches profile data"
If fabrications are detected: "FABRICATION DETECTED: [list specific fabricated items]"`;
}

// Clean AI output - remove JSON artifacts and meta-text
function cleanAIOutput(content: string): string {
  let cleaned = content || '';

  // Remove JSON wrapper patterns
  cleaned = cleaned.replace(/^\s*\{\s*"(coverLetter|motivationLetter|cv|letter|portfolio|proposal)"\s*:\s*"/i, '');
  cleaned = cleaned.replace(/"\s*\}\s*$/i, '');

  // Remove markdown code blocks
  cleaned = cleaned.replace(/```[a-z]*\n?/gi, '');
  cleaned = cleaned.replace(/```/g, '');

  // Remove meta-commentary at the start
  cleaned = cleaned.replace(/^Here is (the|your|a) (motivation letter|cover letter|CV|resume|portfolio|proposal)[:\s]*/i, '');
  cleaned = cleaned.replace(/^(Below is|I've created|I have written)[^.]*\.\s*/i, '');

  // Remove em-dashes and replace with regular dashes
  cleaned = cleaned.replace(/—/g, '-');
  cleaned = cleaned.replace(/–/g, '-');

  // Remove escaped newlines and fix formatting
  cleaned = cleaned.replace(/\\n/g, '\n');
  cleaned = cleaned.replace(/\\"/g, '"');

  // Remove any remaining JSON artifacts
  cleaned = cleaned.replace(/^\s*[\[{]/, '');
  cleaned = cleaned.replace(/[\]}]\s*$/, '');

  // Trim whitespace
  cleaned = cleaned.trim();

  return cleaned;
}

function stripLetterGreetingAndClosing(text: string, isGerman: boolean): string {
  let out = (text || '').trim();

  // Kill typical greeting lines
  const greetingPatterns = isGerman
    ? [
        /^\s*(sehr\s+geehrte[rn]?|liebe[rn]?|hallo)\b[^\n]*\n+/i,
        /^\s*\b(guten\s+tag|guten\s+morgen|guten\s+abend)\b[^\n]*\n+/i,
      ]
    : [
        /^\s*dear\b[^\n]*\n+/i,
        /^\s*to\s+the\s+hiring\s+manager\b[^\n]*\n+/i,
        /^\s*hello\b[^\n]*\n+/i,
      ];

  for (const re of greetingPatterns) {
    out = out.replace(re, '').trim();
  }

  // Kill common closings
  const closingPatterns = isGerman
    ? [
        /\n\s*(mit\s+freundlichen\s+gr\u00fc\u00dfen|freundliche\s+gr\u00fc\u00dfe|beste\s+gr\u00fc\u00dfe|hochachtungsvoll)[^\n]*$/i,
      ]
    : [
        /\n\s*(kind\s+regards|best\s+regards|sincerely|yours\s+sincerely|yours\s+faithfully)[^\n]*$/i,
      ];

  for (const re of closingPatterns) {
    out = out.replace(re, '').trim();
  }

  // If the model repeats applicant name at end, strip it.
  out = out.replace(/\n\s*[A-Z][A-Za-z\-\s]{2,}\s*$/i, '').trim();

  return out;
}

function detectJobLanguage(job: any): { isGerman: boolean; targetLanguage: 'GERMAN' | 'ENGLISH' } {
  const jobText = `${job?.job_title || ''} ${job?.required_skills || ''} ${job?.description || ''}`.toLowerCase();
  // German-specific signals (keep fast and simple, but better than a tiny list)
  const germanSignals = [
    'kenntnisse', 'erfahrung', 'aufgaben', 'profil', 'wir bieten', 'bewerbung', 'anschreiben', 'lebenslauf',
    'm/w/d', 'ihr profil', 'ihre aufgaben', 'anforderungen', 'qualifikation', 'teamf\u00e4higkeit', 'selbst\u00e4ndig',
    'unbefristet', 'vollzeit', 'teilzeit', 'standort', 'deutsch',
    'entwickler', 'ingenieur', 'manager', 'studium', 'abschluss'
  ];
  const isGerman = germanSignals.some(k => jobText.includes(k));
  return { isGerman, targetLanguage: isGerman ? 'GERMAN' : 'ENGLISH' };
}

function getJobDateFolder(job: any, isGerman: boolean): string {
  // Use date_imported if present, else today.
  const raw = job?.date_imported || job?.dateImported || job?.date_scraped || job?.dateScraped;
  let d: Date;
  if (raw) {
    const parsed = new Date(raw);
    d = isNaN(parsed.getTime()) ? new Date() : parsed;
  } else {
    d = new Date();
  }
  // Always YYYY-MM-DD (user confirmed)
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

function normalizeProfileArrays(profile: any): any {
  const parseField = (field: any) => {
    if (!field) return [];
    if (Array.isArray(field)) return field;
    if (typeof field === 'string') {
      try { return JSON.parse(field); } catch { return []; }
    }
    return [];
  };

  return {
    ...profile,
    experiences: parseField(profile.experiences),
    educations: parseField(profile.educations),
    skills: parseField(profile.skills),
    licenses: parseField(profile.licenses),
    languages: parseField(profile.languages)
  };
}

function tokenize(text: string): string[] {
  return String(text || '')
    .toLowerCase()
    .replace(/[^a-z\u00c0-\u017F0-9\+\#\.\-\s]/g, ' ')
    .split(/\s+/)
    .map(t => t.trim())
    .filter(t => t.length >= 2);
}

function computeRelevanceScore(itemText: string, jobTokens: Set<string>): number {
  const tokens = tokenize(itemText);
  let score = 0;
  for (const t of tokens) {
    if (jobTokens.has(t)) score += 3;
  }
  // Bonus for exact phrase contains
  const lower = String(itemText || '').toLowerCase();
  for (const jt of Array.from(jobTokens)) {
    if (jt.length >= 4 && lower.includes(jt)) score += 1;
  }
  return score;
}

function filterProfileForJob(userProfile: any, job: any): { profile: any; relevantSkills: string[]; relevantCerts: string[] } {
  const jobText = `${job?.job_title || ''} ${job?.required_skills || ''} ${job?.description || ''}`;
  const jobTokens = new Set(tokenize(jobText));

  const skillsRaw: any[] = Array.isArray(userProfile?.skills) ? userProfile.skills : [];
  const certsRaw: any[] = Array.isArray(userProfile?.licenses) ? userProfile.licenses : [];

  const skillStrings = skillsRaw.map((s: any) => {
    if (typeof s === 'string') return s;
    return s?.name || s?.title || JSON.stringify(s);
  });

  const certStrings = certsRaw.map((c: any) => {
    if (typeof c === 'string') return c;
    return c?.name || c?.title || c?.issuer || JSON.stringify(c);
  });

  const scoredSkills = skillStrings
    .map(s => ({ s, score: computeRelevanceScore(s, jobTokens) }))
    .sort((a, b) => b.score - a.score || a.s.localeCompare(b.s));

  const scoredCerts = certStrings
    .map(s => ({ s, score: computeRelevanceScore(s, jobTokens) }))
    .sort((a, b) => b.score - a.score || a.s.localeCompare(b.s));

  // Strict caps requested
  const relevantSkills = scoredSkills.filter(x => x.score > 0).slice(0, 7).map(x => x.s);
  const relevantCerts = scoredCerts.filter(x => x.score > 0).slice(0, 5).map(x => x.s);

  // If none match, fallback to a small subset (still capped)
  const finalSkills = relevantSkills.length > 0 ? relevantSkills : skillStrings.slice(0, 5);
  const finalCerts = relevantCerts.length > 0 ? relevantCerts : certStrings.slice(0, 3);

  const filteredProfile = {
    ...userProfile,
    skills: finalSkills,
    licenses: finalCerts
  };

  return { profile: filteredProfile, relevantSkills: finalSkills, relevantCerts: finalCerts };
}

// Document type definitions
const DOC_TYPES = [
  { key: 'cv', label: 'CV', optionKey: 'cv' },
  { key: 'motivation_letter', label: 'Motivation Letter', optionKey: 'motivationLetter' },
  { key: 'cover_letter', label: 'Cover Letter', optionKey: 'coverLetter' },
  { key: 'portfolio', label: 'Portfolio', optionKey: 'portfolio' },
  { key: 'proposal', label: 'Proposal', optionKey: 'proposal' }
];

// Generate HTML template for document
function generateDocumentHTML(content: string, docType: string, userProfile: any, job: any, isGerman: boolean): string {
  const title = `${docType} - ${userProfile?.name || 'Applicant'} - ${job?.company_name || 'Company'}`;
  const isLetter = docType.toLowerCase().includes('letter');

  const currentDate = new Date().toLocaleDateString(isGerman ? 'de-DE' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  // Template owns greeting/closing to avoid doubles.
  const salutation = isGerman ? 'Sehr geehrte Damen und Herren,' : 'Dear Hiring Manager,';
  const closing = isGerman ? 'Mit freundlichen Grüßen' : 'Kind regards,';

  // Ensure content doesn't have redundant headers if AI generated them
  let cleanContent = content;
  if (isLetter) {
    cleanContent = stripLetterGreetingAndClosing(cleanContent, isGerman);
  }

  return `<!DOCTYPE html>
<html lang="${isGerman ? 'de' : 'en'}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    
    * { margin: 0; padding: 0; box-sizing: border-box; }
    
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 60px 80px;
      background: #fff;
    }
    
    .letterhead {
      display: flex;
      justify-content: space-between;
      margin-bottom: 50px;
      border-bottom: 1px solid #eee;
      padding-bottom: 20px;
    }
    
    .applicant-info {
      text-align: left;
    }
    
    .applicant-name {
      font-size: 24px;
      font-weight: 700;
      color: #0077b5;
      margin-bottom: 5px;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    
    .applicant-contact {
      font-size: 13px;
      color: #666;
    }
    
    .applicant-contact p { margin: 1px 0; }
    
    .date-section {
      text-align: right;
      font-size: 14px;
      color: #444;
      margin-bottom: 30px;
    }
    
    .recipient-info {
      margin-bottom: 35px;
      font-size: 14px;
      color: #222;
      line-height: 1.5;
    }
    
    .recipient-info p { margin: 2px 0; }
    
    .salutation {
      margin-bottom: 20px;
      font-weight: 600;
      font-size: 15px;
    }
    
    .content {
      font-size: 15px;
      text-align: justify;
      white-space: pre-wrap;
      margin-bottom: 40px;
    }
    
    .signature {
      margin-top: 40px;
    }
    
    .closing {
      margin-bottom: 30px;
      font-size: 15px;
    }
    
    .signature-name {
      font-weight: 700;
      font-size: 16px;
      color: #0077b5;
    }

    @media print {
      body { padding: 40px; }
      .letterhead { margin-bottom: 30px; }
    }
  </style>
</head>
<body>
  ${isLetter ? `
  <div class="letterhead">
    <div class="applicant-info">
      <div class="applicant-name">${userProfile?.name || 'Your Name'}</div>
      <div class="applicant-contact">
        ${userProfile?.email ? `<p>${userProfile.email}</p>` : ''}
        ${userProfile?.phone ? `<p>${userProfile.phone}</p>` : ''}
        ${userProfile?.location ? `<p>${userProfile.location}</p>` : ''}
      </div>
    </div>
    <div style="text-align: right; font-size: 12px; color: #999;">
      ${docType.toUpperCase()}
    </div>
  </div>
  
  <div class="date-section">${currentDate}</div>
  
  <div class="recipient-info">
    <p><strong>To: Hiring Manager</strong></p>
    <p>${job?.company_name || 'Company Name'}</p>
    ${job?.location ? `<p>${job.location}</p>` : ''}
  </div>
  
  <div class="salutation">${salutation}</div>
  ` : `
  <div class="header" style="margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #0077b5;">
    <div style="font-size: 32px; font-weight: 700; color: #0077b5; margin-bottom: 5px;">${userProfile?.name || 'Your Name'}</div>
    <div style="font-size: 18px; color: #555; margin-bottom: 15px;">${userProfile?.title || 'Professional Title'}</div>
    <div style="font-size: 14px; color: #666; display: flex; gap: 20px;">
      ${userProfile?.email ? `<span>📧 ${userProfile.email}</span>` : ''}
      ${userProfile?.phone ? `<span>📱 ${userProfile.phone}</span>` : ''}
      ${userProfile?.location ? `<span>📍 ${userProfile.location}</span>` : ''}
    </div>
  </div>
  `}
  
  <div class="content">${cleanContent.replace(/\n/g, '<br>')}</div>
  
  ${isLetter ? `
  <div class="signature">
    <div class="closing">${closing}</div>
    <div class="signature-name">${userProfile?.name || 'Your Name'}</div>
  </div>
  ` : ''}
</body>
</html>`;
}

// Generate CV HTML with full profile
function generateCVHTML(content: string, userProfile: any, job: any, isGerman: boolean): string {
  const experiences = userProfile?.experiences || [];
  const educations = userProfile?.educations || [];
  // NOTE: userProfile.skills and userProfile.licenses are expected to be PRE-FILTERED
  // to only the most relevant items (5-7 skills, 3-5 certifications).
  const skills = userProfile?.skills || [];
  const certifications = userProfile?.licenses || [];

  let experiencesHTML = '';
  if (Array.isArray(experiences)) {
    experiencesHTML = experiences.map((exp: any) => `
      <div class="experience-item">
        <div class="item-header">
          <div>
            <span class="item-title">${exp.title || exp.job_title || exp}</span>
            ${(exp.company || exp.company_name) ? `<span class="item-company"> at ${exp.company || exp.company_name}</span>` : ''}
          </div>
          <span class="item-date">${exp.startDate || exp.start_date || ''} - ${exp.endDate || exp.end_date || 'Present'}</span>
        </div>
        ${(exp.location || exp.city) ? `<div style="color: #666; font-size: 13px;">${exp.location || exp.city}</div>` : ''}
        ${(exp.description || exp.summary) ? `<div class="item-description">${exp.description || exp.summary}</div>` : ''}
      </div>
    `).join('');
  }
  
  let educationsHTML = '';
  if (Array.isArray(educations)) {
    educationsHTML = educations.map((edu: any) => `
      <div class="education-item">
        <div class="item-header">
          <div>
            <span class="item-title">${edu.degree || edu.qualification || edu}</span>
            ${(edu.field || edu.major) ? `<span class="item-company"> in ${edu.field || edu.major}</span>` : ''}
          </div>
          <span class="item-date">${edu.startYear || edu.start_year || edu.startDate || ''} - ${edu.endYear || edu.end_year || edu.endDate || ''}</span>
        </div>
        ${(edu.school || edu.university || edu.institution) ? `<div style="color: #666; font-size: 13px;">${edu.school || edu.university || edu.institution}</div>` : ''}
      </div>
    `).join('');
  }
  
  let skillsHTML = '';
  if (Array.isArray(skills) && skills.length > 0) {
    skillsHTML = `<div class="skills-list">${skills.map((s: string) => `<span class="skill-tag">${s}</span>`).join('')}</div>`;
  }
  
  let certsHTML = '';
  if (Array.isArray(certifications) && certifications.length > 0) {
    certsHTML = `<div class="skills-list">${certifications.map((c: string) => `<span class="skill-tag" style="background: #fff3e0; color: #ef6c00;">${c}</span>`).join('')}</div>`;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CV - ${userProfile?.name || 'Applicant'}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    
    * { margin: 0; padding: 0; box-sizing: border-box; }
    
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.5;
      color: #1a1a1a;
      max-width: 850px;
      margin: 0 auto;
      padding: 30px 40px;
      background: #fff;
    }
    
    .header {
      display: flex;
      gap: 20px;
      align-items: center;
      margin-bottom: 25px;
      padding-bottom: 20px;
      border-bottom: 3px solid #0077b5;
    }
    
    .header-photo {
      width: 100px;
      height: 100px;
      border-radius: 50%;
      object-fit: cover;
      border: 3px solid #0077b5;
    }
    
    .header-info { flex: 1; }
    .name { font-size: 32px; font-weight: 700; color: #0077b5; }
    .title { font-size: 18px; color: #444; margin: 5px 0; }
    .contact { font-size: 13px; color: #666; display: flex; flex-wrap: wrap; gap: 15px; margin-top: 8px; }
    
    .main { display: grid; grid-template-columns: 1fr 300px; gap: 30px; }
    .left-column { }
    .right-column { }
    
    .section { margin-bottom: 20px; }
    .section-title {
      font-size: 13px;
      font-weight: 700;
      color: #0077b5;
      text-transform: uppercase;
      letter-spacing: 1.5px;
      margin-bottom: 12px;
      padding-bottom: 5px;
      border-bottom: 2px solid #e0e0e0;
    }
    
    .summary { font-size: 14px; color: #333; text-align: justify; }
    
    .experience-item, .education-item { margin-bottom: 18px; }
    .item-header { display: flex; justify-content: space-between; flex-wrap: wrap; }
    .item-title { font-weight: 600; font-size: 15px; color: #1a1a1a; }
    .item-company { color: #666; font-size: 14px; }
    .item-date { color: #888; font-size: 12px; }
    .item-description { font-size: 13px; color: #444; margin-top: 5px; }
    
    .skills-list { display: flex; flex-wrap: wrap; gap: 6px; }
    .skill-tag {
      background: #e3f2fd;
      color: #0077b5;
      padding: 4px 10px;
      border-radius: 12px;
      font-size: 11px;
      font-weight: 500;
    }
    
    @media print {
      body { padding: 15px; font-size: 12px; }
      .section-title { font-size: 11px; }
      .name { font-size: 24px; }
    }
  </style>
</head>
<body>
  <div class="header">
    ${userProfile?.photo ? `<img src="${userProfile.photo}" class="header-photo" alt="Photo">` : ''}
    <div class="header-info">
      <div class="name">${userProfile?.name || 'Your Name'}</div>
      <div class="title">${userProfile?.title || 'Professional Title'}</div>
      <div class="contact">
        ${userProfile?.email ? `<span>📧 ${userProfile.email}</span>` : ''}
        ${userProfile?.phone ? `<span>📱 ${userProfile.phone}</span>` : ''}
        ${userProfile?.location ? `<span>📍 ${userProfile.location}</span>` : ''}
      </div>
    </div>
  </div>
  
  <div class="main">
    <div class="left-column">
      ${userProfile?.summary ? `
        <div class="section">
          <div class="section-title">${isGerman ? 'Beruflicher Werdegang' : 'Professional Summary'}</div>
          <div class="summary">${userProfile.summary}</div>
        </div>
      ` : ''}
      
      ${experiencesHTML ? `
        <div class="section">
          <div class="section-title">${isGerman ? 'Berufserfahrung' : 'Work Experience'}</div>
          ${experiencesHTML}
        </div>
      ` : ''}
      
      ${educationsHTML ? `
        <div class="section">
          <div class="section-title">${isGerman ? 'Ausbildung' : 'Education'}</div>
          ${educationsHTML}
        </div>
      ` : ''}
    </div>
    
    <div class="right-column">
      ${skillsHTML ? `
        <div class="section">
          <div class="section-title">${isGerman ? 'Kenntnisse' : 'Skills'}</div>
          ${skillsHTML}
        </div>
      ` : ''}
      
      ${certsHTML ? `
        <div class="section">
          <div class="section-title">${isGerman ? 'Zertifizierungen' : 'Certifications'}</div>
          ${certsHTML}
        </div>
      ` : ''}
      
      ${userProfile?.languages?.length > 0 ? `
        <div class="section">
          <div class="section-title">${isGerman ? 'Sprachen' : 'Languages'}</div>
          <div class="skills-list">
            ${userProfile.languages.map((l: string) => `<span class="skill-tag" style="background: #e8f5e9; color: #388e3c;">${l}</span>`).join('')}
          </div>
        </div>
      ` : ''}
    </div>
  </div>
</body>
</html>`;
}

// Save document to file with organized directory structure
function saveDocumentFile(content: string, jobId: number, docType: string, format: 'html' | 'txt' = 'html', companyName?: string, position?: string): string {
  // Use organized directory if company/position available, otherwise use base directory
  const docsDir = (companyName && position) 
    ? getOrganizedDocsDir(companyName, position)
    : getDocsDir();
    
  const timestamp = Date.now();
  const fileName = `${docType}_job${jobId}_${timestamp}.${format}`;
  const filePath = path.join(docsDir, fileName);
  
  console.log(`Saving document to: ${filePath}`);
  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`Document saved: ${filePath}`);
  
  return filePath;
}

// Main document generation function
export async function generateTailoredDocs(job: any, userId: number, thinker: any, auditor: any, options: any, callAI: Function) {
  const db = getDatabase();
  
  // Detect language from job description
  const jobText = (job.job_title + ' ' + (job.description || '')).toLowerCase();
  const germanKeywords = ['kenntnisse', 'erfahrung', 'aufgaben', 'profil', 'wir bieten', 'entwickler', 'ingenieur', 'manager', 'abschluss', 'studium', 'bewerbung', 'anschreiben', 'lebenslauf'];
  const isGerman = germanKeywords.some(k => jobText.includes(k));
  const targetLanguage = isGerman ? 'GERMAN' : 'ENGLISH';
  
  // Get profile based on Thinker's source settings
  let userProfile = await getProfileByThinkerSource(userId, thinker);
  
  if (!userProfile) {
    await logAction(userId, 'ai_thinker', '❌ No user profile found. Please create your profile first.', 'failed', false);
    return;
  }

  // Robust parsing of profile fields (handle both JSON strings and objects)
  const parseField = (field: any) => {
    if (!field) return [];
    if (Array.isArray(field)) return field;
    if (typeof field === 'string') {
      try { return JSON.parse(field); } catch (e) { return []; }
    }
    return [];
  };

  userProfile = {
    ...userProfile,
    experiences: parseField(userProfile.experiences),
    educations: parseField(userProfile.educations),
    skills: parseField(userProfile.skills),
    licenses: parseField(userProfile.licenses),
    languages: parseField(userProfile.languages)
  };

  // Get word limits from Thinker settings
  const motivationLetterWordLimit = thinker?.motivation_letter_word_limit || '450';
  const coverLetterWordLimit = thinker?.cover_letter_word_limit || '280';
  const cvPageLimit = thinker?.cv_page_limit || '2';

  // Step 0: Research Company
  let companyResearch = "";
  try {
    await logAction(userId, 'ai_thinker', `🔍 Researching ${job.company_name} mission and history...`, 'in_progress');
    companyResearch = await getCompanyInfo(job.company_name, userId, callAI);
  } catch (e) {
    console.error("Research failed:", e);
    companyResearch = "Research unavailable.";
  }

  for (const type of DOC_TYPES) {
    if (options[type.optionKey]) {
      try {
        await logAction(userId, 'ai_thinker', `✍️ Generating tailored ${type.label} for ${job.company_name}`, 'in_progress');
        await runQuery('UPDATE job_listings', { id: String(job.id), [`${type.key}_status`]: 'generating', [`${type.key}_rejection_reason`]: null });

        await logAction(userId, 'ai_thinker', `✍️ Generating ${type.label} (Auditor disabled - user choice respected)`, 'in_progress');
        
        // Build the prompt based on document type with custom word limits
        const thinkerPrompt = buildThinkerPrompt(
          type.key, 
          type.label, 
          userProfile, 
          job, 
          companyResearch, 
          '', 
          { motivationLetterWordLimit, coverLetterWordLimit, cvPageLimit, targetLanguage }
        );
        
        let rawContent = await callAI(thinker, thinkerPrompt);
        
        if (!rawContent || rawContent.startsWith('Error:')) {
          throw new Error(rawContent || 'AI returned empty content');
        }
        
        const content = cleanAIOutput(rawContent);
        await logAction(userId, 'ai_thinker', `✅ ${type.label} generated successfully`, 'completed', true);

        // Generate HTML file
        let htmlContent: string;
        if (type.key === 'cv') {
          htmlContent = generateCVHTML(content, userProfile, job, isGerman);
        } else {
          htmlContent = generateDocumentHTML(content, type.label, userProfile, job, isGerman);
        }
        
        const filePath = saveDocumentFile(htmlContent, job.id, type.key, 'html', job.company_name, job.job_title);
        
        const docId = Date.now() + Math.floor(Math.random() * 1000);
        await runQuery('INSERT INTO documents', {
          id: docId,
          job_id: String(job.id),
          user_id: userId,
          document_type: type.key,
          content: content,
          file_path: filePath,
          version: 1,
          status: 'final',
          created_at: new Date().toISOString()
        });

        await runQuery('UPDATE job_listings', { 
          id: String(job.id), 
          [`${type.key}_status`]: 'auditor_done',
          [`${type.key}_path`]: filePath,
          [`${type.key}_rejection_reason`]: null
        });
        
        await logAction(userId, 'ai_thinker', `📄 ${type.label} saved to: ${filePath}`, 'completed', true);
        
        // Convert to PDF immediately
        try {
          const { convertHtmlToPdf } = require('./pdf-export');
          const pdfResult = await convertHtmlToPdf(filePath, userId);
          
          if (pdfResult.success && pdfResult.pdfPath) {
            await runQuery('UPDATE job_listings', { 
              id: String(job.id), 
              [`${type.key}_path`]: pdfResult.pdfPath 
            });
            await runQuery('UPDATE documents', {
              id: docId,
              file_path: pdfResult.pdfPath
            });
            await logAction(userId, 'pdf', `✅ PDF created: ${path.basename(pdfResult.pdfPath)}`, 'completed', true);
          }
        } catch (pdfErr) {
          console.error('Auto-PDF conversion failed:', pdfErr);
        }

      } catch (e: any) {
        console.error(`Error generating ${type.key}:`, e);
        await runQuery('UPDATE job_listings', { id: String(job.id), [`${type.key}_status`]: 'failed' });
        await logAction(userId, 'ai_thinker', `❌ Error: ${e.message}`, 'failed', false);
      }
    }
  }
}

// Build Thinker prompt based on document type
function buildThinkerPrompt(
  docKey: string, 
  docLabel: string, 
  userProfile: any, 
  job: any, 
  companyResearch: string, 
  feedback: string,
  wordLimits?: { motivationLetterWordLimit: string; coverLetterWordLimit: string; cvPageLimit?: string; targetLanguage?: string }
): string {
  const motivationWordLimit = wordLimits?.motivationLetterWordLimit || '450';
  const coverWordLimit = wordLimits?.coverLetterWordLimit || '280';
  const cvPageLimit = wordLimits?.cvPageLimit || '2';
  
  const baseContext = `\nCRITICAL LANGUAGE REQUIREMENT: You MUST write the entire document in ${targetLanguage}. This is a non-negotiable requirement.\n
USER PROFILE:
Name: ${userProfile?.name || 'N/A'}
Title: ${userProfile?.title || 'N/A'}
Location: ${userProfile?.location || 'N/A'}
Email: ${userProfile?.email || 'N/A'}
Phone: ${userProfile?.phone || 'N/A'}
Summary: ${userProfile?.summary || 'N/A'}
Experiences: ${JSON.stringify(userProfile?.experiences || [])}
Skills: ${JSON.stringify(userProfile?.skills || [])}
Education: ${JSON.stringify(userProfile?.educations || [])}
Certifications: ${JSON.stringify(userProfile?.licenses || [])}
Languages: ${JSON.stringify(userProfile?.languages || [])}

JOB DETAILS:
Title: ${job.job_title}
Company: ${job.company_name}
Location: ${job.location || 'N/A'}
Type: ${job.job_type || 'N/A'}
Description: ${job.description || 'N/A'}
Required Skills: ${job.required_skills || 'N/A'}

COMPANY RESEARCH:
${companyResearch || 'No additional company research available. Focus on what can be inferred from the job description.'}

${feedback ? `PREVIOUS FEEDBACK FROM AUDITOR: ${feedback}\nPlease fix these issues in the new version.` : ''}
`;

  const prompts: Record<string, string> = {
    cv: `You are a professional CV/Resume writer. Create a tailored CV for this job application.

CRITICAL LANGUAGE REQUIREMENT: You MUST write the entire CV in ${targetLanguage}. This includes all section headings, job descriptions, and summaries. If the job description is in German, the CV MUST be 100% in German.

${baseContext}

RELEVANCE RULE:
- Include ONLY skills and certifications that are DIRECTLY RELEVANT to this specific job.
- If a certification or skill has no connection to the job requirements, OMIT IT.
- Quality over quantity. A focused CV is better than a long list of irrelevant items.

CRITICAL RULES - VIOLATIONS WILL CAUSE REJECTION:
1. DO NOT fabricate or hallucinate any information - use ONLY data from the provided profile
2. DO NOT invent job titles, companies, dates, or achievements not in the profile
3. DO NOT include any JSON formatting or markdown code blocks
4. DO NOT add meta-commentary like "Here is your CV"

NOTE: CV generation is NOT subject to word limits. Use the full profile data.

REQUIREMENTS:
1. Tailor the CV specifically to the job requirements.
2. RELEVANCE FILTER: Your profile contains many skills and certifications. You MUST ONLY include those that are DIRECTLY RELEVANT to this specific position. If a skill or certification is not mentioned or implied as useful in the job description, DO NOT include it. A concise, relevant CV is mandatory. DO NOT list more than 5-7 key skills and 3-5 relevant certifications.
3. Highlight relevant experiences and skills that match the job description - but ONLY from the provided profile.
3. Use action verbs and quantify achievements where the data exists in the profile
4. Keep it ATS-friendly (no tables, columns, graphics)
5. Include contact information at the top (from the profile)
6. LANGUAGE: You MUST write the entire document in the SAME LANGUAGE as the job description provided above. If the job is in German, write in German. If in English, write in English.
7. Structure: Contact Info, Professional Summary, Work Experience, Education, Skills, Certifications, Languages

ATS OPTIMIZATION:
- IMPORTANT: Include relevant KEYWORDS from the job description in your CV where they genuinely apply
- If the job mentions specific tools, technologies, or skills that relate to your experience, use those exact terms
- Mirror the language and terminology used in the job posting where appropriate
- If there are skill gaps, don't fabricate - instead, emphasize transferable skills and related experience

STRUCTURE:
- CONTACT: Name, Title, Email, Phone, Location (from profile)
- PROFESSIONAL SUMMARY: 3-4 sentences summarizing experience relevant to this role. If there's a skill gap, briefly mention eagerness to apply existing skills to new challenges.
- WORK EXPERIENCE: List jobs from profile with title, company, dates, and bullet points
- EDUCATION: List degrees from profile
- SKILLS: List skills from profile, prioritizing those matching job requirements
- CERTIFICATIONS: List certifications from profile
- LANGUAGES: List languages from profile

OUTPUT FORMAT: Return ONLY the CV content in clean text format. Use clear section headings.`,

    motivation_letter: `You are an expert Motivation Letter writer. Create a compelling, HUMAN-SOUNDING motivation letter.

${baseContext}

WORD LIMIT: ${motivationWordLimit} words (this is configurable by the user)

CRITICAL RULES - VIOLATIONS WILL CAUSE REJECTION:
1. DO NOT start with "Here is the motivation letter:" or any similar meta-text
2. DO NOT include JSON formatting like { "motivationLetter": ... }
3. DO NOT mention "I could not find..." or "Research was unavailable"
4. DO NOT use long em-dashes (—), use regular dashes (-) only
5. DO NOT use clichés: "I am thrilled", "passionate professional", "fast-paced world"
6. DO NOT start sentences with "I have..." or "I am..." repeatedly
7. DO NOT fabricate or hallucinate information - use ONLY data from the provided profile
8. DO NOT invent company facts not mentioned in the research - if unsure, focus on what's in the job posting
9. Output ONLY the letter body content. DO NOT include a date, recipient address, salutation (like "Dear..."), or closing (like "Kind regards"). The system will provide these automatically.
10. MUST end with proper sign-off: "Kind regards," followed by the applicant's full name

HANDLING SKILL GAPS (IMPORTANT):
- If the candidate's profile doesn't perfectly match all job requirements, DO NOT reject or avoid the task
- Instead, express genuine enthusiasm to learn and adapt to the role's requirements
- Highlight transferable skills that relate to the missing requirements
- Show willingness to grow: phrases like "I am eager to expand my expertise in..." or "I look forward to developing my skills in..."
- Frame any gaps as growth opportunities, not weaknesses

STRUCTURE (follow exactly):
1. HEADER: Date, Company Address, "Dear Hiring Manager,"
2. OPENING (1 paragraph): State who you are, what position, and ONE compelling reason why this company
3. COMPANY CONNECTION (1 paragraph): Reference something specific about the company - their products, services, recent news, or values. If research is limited, focus on what's clear from the job posting
4. YOUR VALUE (2 paragraphs): 
   - First: Your most relevant experience with SPECIFIC metrics/achievements FROM YOUR ACTUAL PROFILE
   - Second: How your skills directly solve their needs OR how your transferable skills and eagerness to learn make you a strong candidate
5. WHY THIS ROLE (1 paragraph): Personal motivation - career goals, growth opportunity, alignment. EXPRESS ENTHUSIASM to learn any skills you may be developing.
6. CLOSING: Thank them, express enthusiasm for an interview
7. SIGN-OFF: "Kind regards," + new line + "${userProfile?.name || '[Your Name]'}"

MUST INCLUDE:
- At least 2 specific achievements with numbers/metrics FROM THE PROVIDED PROFILE
- At least 1 specific reference to the company (product, service, or value)
- Smooth transitions between paragraphs
- Professional but warm tone
- Proper sign-off with full name
- If skill gaps exist: Express enthusiasm to learn and adapt

Length: Approximately ${motivationWordLimit} words. This is a formal document.
LANGUAGE: You MUST write the entire document in the SAME LANGUAGE as the job description provided above. If the job is in German, write in German. If in English, write in English.

Return ONLY the motivation letter content, starting directly with the date and ending with the sign-off.`,

    cover_letter: `You are an expert Cover Letter writer. Create a concise, professional cover letter.

${baseContext}

WORD LIMIT: ${coverWordLimit} words (this is configurable by the user)

CRITICAL RULES - VIOLATIONS WILL CAUSE REJECTION:
1. DO NOT include any JSON formatting like { "coverLetter": ... }
2. DO NOT start with meta-text like "Here is the cover letter:"
3. DO NOT use long em-dashes (—), use regular dashes (-) only
4. DO NOT fabricate or hallucinate information not provided in the profile
5. Output ONLY the letter body content. DO NOT include a salutation (like "Dear...") or closing (like "Kind regards"). The system will provide these automatically.

HANDLING SKILL GAPS:
- If there are gaps between the job requirements and the candidate's profile, highlight transferable skills
- Express genuine enthusiasm to learn and adapt
- Frame gaps as growth opportunities: "I am eager to develop my expertise in..."

REQUIREMENTS:
1. Be concise (approximately ${coverWordLimit} words)
2. Address the hiring manager professionally
3. Highlight 2-3 most relevant qualifications with specific examples FROM THE PROVIDED PROFILE ONLY
4. Show enthusiasm for the specific role AND for learning/growing
5. Include a clear call to action
6. No clichés or AI-sounding phrases
7. LANGUAGE: You MUST write the entire document in the SAME LANGUAGE as the job description provided above. If the job is in German, write in German. If in English, write in English.
8. MUST end with proper sign-off: "Kind regards," followed by the applicant's full name

STRUCTURE:
- Opening: "Dear Hiring Manager," then state the position and express interest (1-2 sentences)
- Middle (2 paragraphs): Your relevant qualifications and why you're a great fit
- Closing: Thank them, suggest next steps
- Sign-off: "Kind regards," + new line + "${userProfile?.name || '[Your Name]'}"

Return ONLY the cover letter content, starting with "Dear Hiring Manager," and ending with the sign-off.`,

    portfolio: `You are a Portfolio Description writer. Create a portfolio summary for this job application.

${baseContext}

REQUIREMENTS:
1. Highlight 3-5 most relevant projects or achievements
2. For each project:
   - Brief description (2-3 sentences)
   - Technologies/skills used
   - Measurable impact/results
3. Tailor selection to the job requirements
4. Include links placeholders [Project Link] where appropriate

Return ONLY the portfolio description content.`,

    proposal: `You are a professional Proposal writer. Create a proposal for this job application.

${baseContext}

REQUIREMENTS:
1. Executive Summary: What you propose to do for them
2. Understanding: Show you understand their challenges
3. Approach: How you would tackle the role
4. Value Proposition: What unique value you bring
5. Next Steps: Suggest a meeting or discussion
6. Professional tone, business-focused

Return ONLY the proposal content.`
  };

  return prompts[docKey] || prompts['motivation_letter'];
}

// Build Auditor prompt
function buildAuditorPrompt(docKey: string, docLabel: string, content: string, job: any): string {
  // Get compatibility score and missing skills from job
  const compatScore = job.compatibility_score || 0;
  const missingSkills = job.compatibility_missing_skills ? 
    JSON.parse(job.compatibility_missing_skills) : [];
  
  // Determine job match level
  const isGoldJob = compatScore >= 76; // 76-100%
  const isGreenJob = compatScore >= 51 && compatScore < 76; // 51-75%
  const isYellowJob = compatScore >= 26 && compatScore < 51; // 26-50%
  const isAcceptableJob = compatScore >= 26; // Yellow, Green, or Gold
  
  let flexibilityNote = '';
  
  if (isGoldJob) {
    flexibilityNote = `
**⭐ GOLD JOB (Score: ${compatScore}%) - AUTO-APPROVE ⭐**

YOU MUST RESPOND WITH "APPROVED" FOR THIS DOCUMENT.

This is an EXCELLENT match (76%+). The user is highly qualified.
Your response should be exactly: "APPROVED"

DO NOT look for any issues. DO NOT reject. Just respond "APPROVED".
`;
  } else if (isGreenJob) {
    flexibilityNote = `
**🟢 GREEN JOB (Score: ${compatScore}%) - AUTO-APPROVE 🟢**

YOU MUST RESPOND WITH "APPROVED" FOR THIS DOCUMENT.

This is a GOOD match (51-75%). The user has chosen to apply.
Your response should be exactly: "APPROVED"

DO NOT look for missing skills or quality issues. Just respond "APPROVED".

${missingSkills.length > 0 ? `Note: Some skills may be missing, but the user wants to apply anyway:
- ${missingSkills.slice(0, 5).join('\n- ')}

This is OK. Respond "APPROVED".` : ''}
`;
  } else if (isYellowJob) {
    flexibilityNote = `
**NOTICE - THIS IS A YELLOW JOB (Score: ${compatScore}%):**
This is a reasonable match. The user has chosen to apply despite some gaps.

${missingSkills.length > 0 ? `Missing skills (user is aware):
- ${missingSkills.slice(0, 5).join('\n- ')}

Allow:
- Transferable skills and related experience
- Honest statements about willingness to learn
- Highlighting adjacent experience

DO NOT reject simply because the applicant can't claim direct experience.` : ''}

APPROVE unless there is FABRICATED information or critical format issues.
`;
  }
  
  return `You are the "Auditor" agent. Your job is to review this ${docLabel}.

JOB: ${job.job_title} at ${job.company_name}
COMPATIBILITY SCORE: ${compatScore}%

CONTENT TO REVIEW:
${content}
${flexibilityNote}
**YOUR DECISION RULES:**

1. For GOLD/GREEN jobs (score 51%+): APPROVE unless you find FABRICATED facts
2. For YELLOW jobs (score 26-50%): APPROVE unless you find fabrication or major issues
3. Fabrication means: claiming specific jobs/achievements/certifications the person never had

**THINGS THAT ARE NOT FABRICATION (DO NOT REJECT FOR THESE):**
- Soft skills (leadership, communication, teamwork)
- Transferable experience from related roles
- "Willingness to learn" statements
- General industry knowledge
- Using different words to describe real experience

**FORMAT CHECKS (only reject for severe issues):**
- Language matches job description? (OK if close)
- Has proper greeting? (OK if professional)
- Has proper sign-off? (OK if includes name)
- No obvious placeholders like "[Insert...]"?

**RESPONSE FORMAT:**
If acceptable: respond with exactly "APPROVED"
If has fabrication: respond with "REJECTED: " followed by the specific fabrication found

REMEMBER: You are NOT a gatekeeper. The user chose this job. Help them apply.`;
}

// Export individual document generator for direct calls
export async function generateSingleDocument(
  jobId: number, 
  userId: number, 
  docType: string, 
  thinker: any, 
  auditor: any, 
  callAI: Function
): Promise<{ success: boolean; filePath?: string; error?: string }> {
  const db = getDatabase();
  const job = db.job_listings?.find((j: any) => String(j.id) === String(jobId));
  const userProfile = db.user_profile?.find((p: any) => p.id === userId) || db.user_profile?.[0];
  
  if (!job) return { success: false, error: 'Job not found' };
  if (!userProfile) return { success: false, error: 'User profile not found' };
  
  const options: any = {};
  const typeConfig = DOC_TYPES.find(t => t.key === docType);
  if (typeConfig) {
    options[typeConfig.optionKey] = true;
  }
  
  // Detect language
  const jobText = (job.job_title + ' ' + (job.description || '')).toLowerCase();
  const germanKeywords = ['kenntnisse', 'erfahrung', 'aufgaben', 'profil', 'wir bieten', 'entwickler', 'ingenieur', 'manager', 'abschluss', 'studium', 'bewerbung', 'anschreiben', 'lebenslauf'];
  const isGerman = germanKeywords.some(k => jobText.includes(k));

  await generateTailoredDocs(job, userId, thinker, auditor, options, callAI);
  
  // Refresh job data to get file path
  const updatedJob = db.job_listings?.find((j: any) => String(j.id) === String(jobId));
  const filePath = updatedJob?.[`${docType}_path`];
  
  if (filePath) {
    return { success: true, filePath };
  }
  
  return { success: false, error: 'Document generation failed' };
}